#!/bin/bash

export OPC_ENGINE_SIMULATOR_LOG_LEVEL=debug
export OPC_ENGINE_SIMULATOR_PROJECT_PATH="../examples/example.opcproj"
export OPC_ENGINE_SIMULATOR_SERVER_PORT=39056
export OPC_ENGINE_CONFIGURATION_SERVER_PORT=39057
export OPC_ENGINE_SIMULATOR_ENGINE_DEBUG="true"